services:
  - type: web
    name: prairies-africa-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "./render_build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prairies-africa-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: prairies-africa-db
    plan: free
